--
# number of plotting processes to run in parallel
processes: 10

# total number of plotting cycles; minimum 1
cycles:
  count: 20

chia_path: /home/chia/chia

log_path: /home/chia/plotter/logs

# temp plotting directory
temp_path: /plots/temp

# -2 and -d destination directories
destinations:
  - /store1/plots
  - /store2/plots
  - /store3/plots
  - /store4/plots

chia_conf:
  k: 32
  e: true
  u: 128
  b: 4500
  r: 4
